const SOURCES={nasa:{name:'NASA'},smithsonian:{name:'Smithsonian'},wikimedia:{name:'Wikimedia'}};
const TOPICS=['nature','space','animals','flowers','ocean','architecture','art','landscape','science','history','birds','mountains'];
const DIFFICULTIES=[{pieces:4,rows:2,cols:2,name:'Easy'},{pieces:9,rows:3,cols:3,name:'Relaxed'},{pieces:16,rows:4,cols:4,name:'Classic'},{pieces:25,rows:5,cols:5,name:'Challenge'}];
const $=id=>document.getElementById(id);const state={source:'nasa',images:[],selected:null,difficulty:DIFFICULTIES[1],mode:localStorage.getItem('puzzleMode')||'slider',pieces:[],moves:0,startedAt:0};
const shuffle=a=>{const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}return r};
function show(id,title){document.querySelectorAll('.screen').forEach(s=>s.classList.add('hidden'));$(id).classList.remove('hidden');$('pageTitle').textContent=title;scrollTo({top:0,behavior:'smooth'})}
function sourceUI(){const g=$('sourceCards');g.innerHTML='';Object.entries(SOURCES).forEach(([id,s])=>{const b=document.createElement('button');b.className='source-card'+(state.source===id?' active':'');b.textContent=s.name;b.onclick=()=>{state.source=id;state.images=[];sourceUI();loadImages(false)};g.appendChild(b)})}
function difficultyUI(){const g=$('difficultyGrid');g.innerHTML='';DIFFICULTIES.forEach(d=>{const b=document.createElement('button');b.className='difficulty'+(d.pieces===state.difficulty.pieces?' selected':'');b.innerHTML=`<strong>${d.pieces} pieces</strong><small>${d.name}</small>`;b.onclick=()=>{state.difficulty=d;difficultyUI()};g.appendChild(b)})}
function modeUI(){const g=$('modeGrid');g.innerHTML='';[['slider','Slider','All pieces stay on the board.'],['pieces','Pieces','Move pieces from a tray onto the board.']].forEach(([id,n,d])=>{const b=document.createElement('button');b.className='mode-button'+(state.mode===id?' selected':'');b.innerHTML=`<strong>${n}</strong><small>${d}</small>`;b.onclick=()=>{state.mode=id;localStorage.setItem('puzzleMode',id);modeUI()};g.appendChild(b)})}
async function loadImages(append=true){$('galleryMessage').textContent='Loading pictures…';$('loadMore').disabled=true;try{let a=state.source==='nasa'?await nasa():state.source==='wikimedia'?await wikimedia():await smithsonian();const known=new Set(state.images.map(x=>x.url));a=a.filter(x=>x.url&&!known.has(x.url));state.images=append?state.images.concat(a):a;const g=$('gallery');if(!append)g.innerHTML='';a.forEach(image=>{const b=document.createElement('button');b.className='image-choice';b.innerHTML=`<img loading="lazy" src="${image.url}" alt="${image.title}"><span>${image.title}</span>`;b.onclick=()=>{state.selected=image;configure()};g.appendChild(b)});$('galleryMessage').textContent=`${state.images.length} pictures loaded.`}catch(e){$('galleryMessage').textContent='Pictures could not be loaded right now. Try again.'}finally{$('loadMore').disabled=false}}
async function nasa(){const q=TOPICS[Math.random()*TOPICS.length|0],page=Math.random()*20|0,r=await fetch(`https://images-api.nasa.gov/search?q=${q}&media_type=image&page=${page}`);if(!r.ok)throw Error();const d=await r.json();return shuffle((d.collection?.items||[]).map(x=>({title:x.data?.[0]?.title||'NASA picture',url:x.links?.find(l=>l.rel==='preview')?.href})).filter(x=>x.url)).slice(0,12)}
async function wikimedia(){const q=TOPICS[Math.random()*TOPICS.length|0],r=await fetch(`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${q}&gsrnamespace=6&gsrlimit=24&prop=imageinfo&iiprop=url&iiurlwidth=900&format=json&origin=*`);if(!r.ok)throw Error();const d=await r.json();return shuffle(Object.values(d.query?.pages||{}).map(x=>({title:(x.title||'').replace(/^File:/,''),url:x.imageinfo?.[0]?.thumburl||x.imageinfo?.[0]?.url})).filter(x=>x.url)).slice(0,12)}
async function smithsonian(){const q=TOPICS[Math.random()*TOPICS.length|0],r=await fetch(`https://api.si.edu/openaccess/api/v1.0/search?q=${q}&api_key=DEMO_KEY`);if(!r.ok)throw Error();const d=await r.json();return shuffle((d.response||[]).map(x=>{const m=(x.content?.descriptiveNonRepeating?.online_media?.media||[])[0];return{title:x.title||'Smithsonian picture',url:m?.thumbnail||m?.content||m?.url}}).filter(x=>x.url)).slice(0,12)}
function configure(){show('configureScreen','Configure puzzle');$('selectedPreview').src=state.selected.url;$('selectedTitle').textContent=state.selected.title;$('selectedSource').textContent=SOURCES[state.source]?.name||'Generated picture';difficultyUI()}
function pieceStyle(p){const d=state.difficulty,r=Math.floor(p.correct/d.cols),c=p.correct%d.cols;return `background-image:url("${p.url}");background-size:${d.cols*100}% ${d.rows*100}%;background-position:${d.cols===1?0:c/(d.cols-1)*100}% ${d.rows===1?0:r/(d.rows-1)*100}%;`}
function start(){const image=state.selected;if(!image)return;let a=shuffle(Array.from({length:state.difficulty.pieces},(_,correct)=>({correct,url:image.url})));while(a.every((p,i)=>p.correct===i))a=shuffle(a);state.pieces=a.map((p,i)=>({...p,id:i}));state.moves=0;state.startedAt=Date.now();state.selected=null;show('playScreen',image.title);$('playTitle').textContent=image.title;$('pieceTray').classList.toggle('hidden',state.mode!=='pieces');$('instruction').textContent=state.mode==='pieces'?'Drag a piece onto the board, or tap a piece and a space.':'Tap a piece, then tap another piece to swap them.';render()}
function render(){state.mode==='slider'?renderSlider():renderPieces()}
function renderSlider(){const b=$('board');b.style.gridTemplateColumns=`repeat(${state.difficulty.cols},1fr)`;b.innerHTML='';state.pieces.forEach((p,i)=>{const x=document.createElement('button');x.className='piece'+(state.selected===i?' selected':'');x.style.cssText=pieceStyle(p);x.onclick=()=>selectSlider(i);b.appendChild(x)});$('progressText').textContent=`${state.pieces.filter((p,i)=>p.correct===i).length} / ${state.pieces.length}`;solved()}
function selectSlider(i){if(state.selected==null){state.selected=i;render();return}if(state.selected===i){state.selected=null;render();return}[state.pieces[state.selected],state.pieces[i]]=[state.pieces[i],state.pieces[state.selected]];state.selected=null;state.moves++;render()}
function renderPieces(){const b=$('board'),t=$('tray');b.style.gridTemplateColumns=`repeat(${state.difficulty.cols},1fr)`;b.innerHTML='';t.innerHTML='';for(let slot=0;slot<state.pieces.length;slot++){const cell=document.createElement('div');cell.className='piece';cell.ondragover=e=>e.preventDefault();cell.ondrop=e=>{e.preventDefault();place(+e.dataTransfer.getData('text'),slot)};const p=state.pieces.find(x=>x.slot===slot);if(p){cell.style.cssText=pieceStyle(p);cell.onclick=()=>{p.slot=undefined;state.moves++;render()}}else cell.onclick=()=>{if(state.selected!=null)place(state.selected,slot)};b.appendChild(cell)}state.pieces.filter(p=>p.slot===undefined).forEach(p=>{const x=document.createElement('button');x.className='tray-piece';x.style.cssText=pieceStyle(p);x.draggable=true;x.dataset.id=p.id;x.onclick=()=>{state.selected=p.id;render()};x.ondragstart=e=>e.dataTransfer.setData('text',p.id);if(state.selected===p.id)x.classList.add('selected');t.appendChild(x)});$('progressText').textContent=`${state.pieces.filter(p=>p.slot===p.correct).length} / ${state.pieces.length}`;solved()}
function place(id,slot){const p=state.pieces.find(x=>x.id===id),old=state.pieces.find(x=>x.slot===slot);if(!p)return;if(old)old.slot=undefined;p.slot=slot;state.selected=null;state.moves++;render()}
function solved(){const yes=state.mode==='slider'?state.pieces.length>0&&state.pieces.every((p,i)=>p.correct===i):state.pieces.length>0&&state.pieces.every(p=>p.slot===p.correct);$('winPanel').classList.toggle('hidden',!yes);if(yes){const s=Math.floor((Date.now()-state.startedAt)/1000);$('winDetails').textContent=`${state.moves} ${state.moves===1?'move':'moves'} · ${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;$('instruction').textContent='You completed the picture.'}}
async function generate(){const key=$('geminiKey').value.trim(),prompt=$('promptInput').value.trim();if(!key){$('makeMessage').textContent='A Gemini API key is needed.';return}if(!prompt){$('makeMessage').textContent='Describe the picture first.';return}$('generateButton').disabled=true;$('makeMessage').textContent='Creating your picture…';try{const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[{text:`Create a family-friendly puzzle image based on: ${prompt}`}]}],generationConfig:{responseModalities:['IMAGE']}})});if(!r.ok)throw Error('Gemini could not create the picture. Check the API key.');const d=await r.json(),p=d?.candidates?.flatMap(c=>c.content?.parts||[]).find(x=>x.inlineData?.data);if(!p)throw Error('Gemini did not return an image.');state.selected={title:'My generated picture',url:`data:${p.inlineData.mimeType||'image/png'};base64,${p.inlineData.data}`};localStorage.setItem('pocketPuzzlesGeminiKey',key);show('configureScreen','Configure puzzle');$('selectedPreview').src=state.selected.url;$('selectedTitle').textContent=state.selected.title;$('selectedSource').textContent='Generated';difficultyUI()}catch(e){$('makeMessage').textContent=e.message}finally{$('generateButton').disabled=false}}
function advanced(open){$('advancedModal').classList.toggle('hidden',!open);document.body.style.overflow=open?'hidden':''}
$('playButton').onclick=()=>{show('libraryScreen','Choose a picture');sourceUI();state.images=[];loadImages(false)};$('makeButton').onclick=()=>show('makeScreen','Make Your Own');$('settingsButton').onclick=()=>{show('settingsScreen','Settings');modeUI()};$('settingsMenuButton').onclick=()=>{show('settingsScreen','Settings');modeUI()};$('libraryBack').onclick=()=>show('homeScreen','What would you like to do?');$('configureBack').onclick=()=>show('libraryScreen','Choose a picture');$('settingsBack').onclick=()=>show('homeScreen','What would you like to do?');$('makeBack').onclick=()=>show('homeScreen','What would you like to do?');$('startButton').onclick=start;$('backButton').onclick=()=>show('libraryScreen','Choose a picture');$('newPuzzleButton').onclick=start;$('loadMore').onclick=()=>loadImages(true);$('advancedButton').onclick=()=>advanced(true);$('closeAdvanced').onclick=()=>advanced(false);$('doneAdvanced').onclick=()=>advanced(false);$('advancedModal').onclick=e=>{if(e.target.dataset.close!==undefined)advanced(false)};$('generateButton').onclick=generate;$('geminiKey').value=localStorage.getItem('pocketPuzzlesGeminiKey')||'';document.addEventListener('keydown',e=>{if(e.key==='Escape')advanced(false)});modeUI();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register(new URL('./sw.js',document.baseURI)).catch(()=>{}));